# Generated by Django 4.0.7 on 2023-03-24 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Upload ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='File Path')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
                ('password', models.CharField(max_length=255, verbose_name='User Password')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Team ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('score', models.PositiveIntegerField(verbose_name='Team Score')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Date Modified')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.upload', verbose_name='Upload ID')),
            ],
        ),
    ]
