# Generated by Django 4.0.7 on 2023-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='mime',
            field=models.CharField(default='', max_length=100, verbose_name='Mime Type'),
        ),
        migrations.AddField(
            model_name='upload',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='File Size(bytes)'),
        ),
    ]
