# Generated by Django 4.0.7 on 2023-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_upload_mime_upload_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AddField(
            model_name='team',
            name='point',
            field=models.PositiveIntegerField(default=1, verbose_name='Team Point'),
            preserve_default=False,
        ),
    ]
