# Generated by Django 4.0.7 on 2023-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_team_score_team_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='point',
            field=models.PositiveIntegerField(null=True, verbose_name='Team Point'),
        ),
    ]
