# Generated by Django 4.0.7 on 2023-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_team_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='Team Point'),
        ),
    ]
