# Generated by Django 4.0.7 on 2023-03-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_team_date_created_alter_team_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Match ID')),
                ('team_1_score', models.PositiveIntegerField(default=0, verbose_name='Team 1 Score')),
                ('team_2_score', models.PositiveIntegerField(default=0, verbose_name='Team 2 Score')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('team_1', models.ManyToManyField(related_name='matches_team_1', to='main.team', verbose_name='Team 1')),
                ('team_2', models.ManyToManyField(related_name='matches_team_2', to='main.team', verbose_name='Team 2')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
