# Generated by Django 4.0.7 on 2023-03-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_team_1', to='main.team', to_field='teamid', verbose_name='Team 1'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_team_2', to='main.team', to_field='teamid', verbose_name='Team 2'),
            preserve_default=False,
        ),
    ]
