# Generated by Django 4.0.7 on 2023-03-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_match_team_1_match_team_1_remove_match_team_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.upload', verbose_name='Upload ID'),
        ),
    ]
